I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 57, in script call
    call ch1
  File "game/ch1.rpy", line 128, in script
    if samename:
  File "game/ch1.rpy", line 128, in <module>
    if samename:
NameError: name 'samename' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 57, in script call
    call ch1
  File "game/ch1.rpy", line 128, in script
    if samename:
  File "renpy/ast.py", line 1893, in execute
    if renpy.python.py_eval(condition):
  File "renpy/python.py", line 2266, in py_eval
    return py_eval_bytecode(code, globals, locals)
  File "renpy/python.py", line 2259, in py_eval_bytecode
    return eval(bytecode, globals, locals)
  File "game/ch1.rpy", line 128, in <module>
    if samename:
NameError: name 'samename' is not defined

Windows-10-10.0.19041
Ren'Py 7.4.8.1895
Tri City Monsters 1.0
Mon Sep 27 08:56:45 2021
