I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 63, in script call
    call ch4
  File "game/ch4.rpy", line 92, in script
    thing "[tHEY!t!c!] [ARE!t] A PALTRY OFFERING AFTER TWO LONG YEARS, MEATSACK."
KeyError: u'tHEY'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 63, in script call
    call ch4
  File "game/ch4.rpy", line 92, in script
    thing "[tHEY!t!c!] [ARE!t] A PALTRY OFFERING AFTER TWO LONG YEARS, MEATSACK."
  File "renpy/ast.py", line 716, in execute
    renpy.exports.say(who, what, *args, **kwargs)
  File "renpy/exports.py", line 1417, in say
    who(what, *args, **kwargs)
  File "renpy/character.py", line 1210, in __call__
    what = self.prefix_suffix("what", self.what_prefix, what, self.what_suffix)
  File "renpy/character.py", line 1129, in prefix_suffix
    return (sub(prefix) + sub(body) + sub(suffix))
  File "renpy/character.py", line 1109, in sub
    return renpy.substitutions.substitute(s, scope=scope, force=force, translate=translate)[0]
  File "renpy/substitutions.py", line 270, in substitute
    s = formatter.vformat(s, (), kwargs)
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 563, in vformat
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 585, in _vformat
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 646, in get_field
  File "/home/tom/ab/renpy-build/tmp/install.linux-x86_64/lib/python2.7/string.py", line 605, in get_value
KeyError: u'tHEY'

Windows-7-6.1.7601-SP1
Ren'Py 7.4.8.1895
Tri City Monsters 1.0
Wed Sep 29 22:50:30 2021
