I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 71, in script call
    call credits
  File "game/script.rpy", line 71, in script call
    call credits
ScriptError: could not find label 'credits'.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 71, in script call
    call credits
  File "renpy/ast.py", line 1485, in execute
    rv = renpy.game.context().call(label, return_site=self.next.name)
  File "game/script.rpy", line 71, in script call
    call credits
  File "renpy/script.py", line 918, in lookup
    raise ScriptError("could not find label '%s'." % str(original))
ScriptError: could not find label 'credits'.

Windows-7-6.1.7601-SP1
Ren'Py 7.4.8.1895
Tri City Monsters 1.0
Thu Sep 30 12:36:43 2021
